import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/Components/NavBar";
import { UserProvider } from "@/Contexts/UserContext";
import Footer from "@/Components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <NavBar />
          {children}
          <Footer/>
        </UserProvider>
      </body>
    </html>
  );
}
